version: 2

jobs:
  lint:
    docker:
      - image: circleci/ruby:2.4.1-node
    working_directory: ~/pingcap/docs-tidb-operator
    steps:
      - checkout
      - run:
          name: "Install markdownlint"
          command: |
            sudo npm install -g markdownlint-cli@0.17.0
      - run:
          name: "Lint"
          command: |
            markdownlint .

  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/pingcap/docs-tidb-operator

    steps:
      - checkout

      - run:
          name: "Special Check for Golang User - YOUR TAB SUCK"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py en/; python3 scripts/merge_by_toc.py zh/

      - run:
          name: "Generate PDF"
          command: bash scripts/generate_pdf.sh;

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "release-1.1" ]; then
              python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-stable-en-manual.pdf;
              python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-stable-zh-manual.pdf;
            fi

workflows:
  version: 2
  lint:
    jobs:
      - lint
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-1.1
