name: external-link-check

on: [pull_request]

jobs:
  base:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # NOTE:
      #  - the check process can be very fast,
      #    but if `-c` is too large then `Too Many Requests (HTTP error 429)` may be reported from `https://github.com/*`.
      #  - we hardcode `--document-root` to `/github/workspace` in the container now.
      #  - we use `http://172.*` as sample addresses in some docs, so we need to exclude them.
      - name: Check external links in zh files
        id: lczh
        uses: peter-evans/link-checker@v1
        with:
          args: -c 32 -d /github/workspace -r -x "http://172.*|https://github.com/.*/pull/.*|https://github.com/.*/issues/.*|https://github.com/[^.\n]*$|http://127.0.0.1.*|http://localhost.*|https://shell.aliyun.com.*|.*.md" zh*

      - name: Check external links in en files
        id: lcen
        uses: peter-evans/link-checker@v1
        with:
          args: -c 32 -d /github/workspace -r -x "http://172.*|https://github.com/.*/pull/.*|https://github.com/.*/issues/.*|https://github.com/[^.\n]*$|http://127.0.0.1.*|http://localhost.*|https://shell.aliyun.com.*|.*.md" en*

      - name: Fail if there were external link errors
        if: ${{ steps.lczh.outputs.exit_code || steps.lcen.outputs.exit_code }}
        run: |
          echo "Please check the broken links reported in previous steps \"Check external links in zh files\" and \"Check external links in en files\"."
          exit ${{ steps.lczh.outputs.exit_code || steps.lcen.outputs.exit_code }}
      # Debug via SSH if previous steps failed
      #- name: Set up tmate session
      #  if: ${{ failure() }}
      #  uses: mxschmitt/action-tmate@v2
