name: Linting
on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale Linter
      uses: errata-ai/vale-action@v1.4.3
      with:
        # Optional
        #styles: |
        #  https://github.com/errata-ai/Google/releases/latest/download/Google.zip

        # Optional
        #config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

        # Optional
        files: ./en

        # Optional
        onlyAnnotateModifiedLines: true
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
